<a href="https://colab.research.google.com/github/Peanut2Butter9/integerpartitions/blob/main/Moh.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

MacMahon's Partitions Function

In [2]:
def MacMahon(a, n):
    if a <= 0 or n <= 0:
        print("Error: 'a' and 'n' must be positive integers.")
        return 0
    total_sum = [0]
    _find_partitions_recursive(n, a, 1, [], total_sum)
    return total_sum[0]

def _find_partitions_recursive(target_n, blocks_left, min_s, heights, total_sum):
    if blocks_left == 1:
        for s in range(min_s, target_n + 1):
            if target_n % s == 0:
                d = target_n // s
                product = d
                for h in heights:
                    product *= h
                total_sum[0] += product
        return

    for s in range(min_s, target_n):
        for d in range(1, (target_n // s) + 1):
            remaining_n = target_n - (d * s)
            min_possible_sum = sum(range(s + 1, s + 1 + (blocks_left - 1)))

            if remaining_n >= min_possible_sum:
                _find_partitions_recursive(
                    remaining_n,
                    blocks_left - 1,
                    s + 1,
                    heights + [d],
                    total_sum
                )

Check M_1(n)

In [3]:
for n in range(1, 100):
  print(n, (MacMahon(1, n)))

1 1
2 3
3 4
4 7
5 6
6 12
7 8
8 15
9 13
10 18
11 12
12 28
13 14
14 24
15 24
16 31
17 18
18 39
19 20
20 42
21 32
22 36
23 24
24 60
25 31
26 42
27 40
28 56
29 30
30 72
31 32
32 63
33 48
34 54
35 48
36 91
37 38
38 60
39 56
40 90
41 42
42 96
43 44
44 84
45 78
46 72
47 48
48 124
49 57
50 93
51 72
52 98
53 54
54 120
55 72
56 120
57 80
58 90
59 60
60 168
61 62
62 96
63 104
64 127
65 84
66 144
67 68
68 126
69 96
70 144
71 72
72 195
73 74
74 114
75 124
76 140
77 96
78 168
79 80
80 186
81 121
82 126
83 84
84 224
85 108
86 132
87 120
88 180
89 90
90 234
91 112
92 168
93 128
94 144
95 120
96 252
97 98
98 171
99 156

Check M_2(n)

In [4]:
for n in range(1, 100):
  print(n, (MacMahon(2, n)))

1 0
2 0
3 1
4 3
5 9
6 15
7 30
8 45
9 67
10 99
11 135
12 175
13 231
14 306
15 354
16 465
17 540
18 681
19 765
20 945
21 1040
22 1305
23 1386
24 1695
25 1779
26 2205
27 2290
28 2754
29 2835
30 3438
31 3480
32 4185
33 4272
34 5076
35 5004
36 6100
37 5985
38 7155
39 7154
40 8325
41 8190
42 9840
43 9471
44 11241
45 11055
46 12870
47 12420
48 14911
49 14058
50 16569
51 16290
52 18795
53 17901
54 21390
55 19998
56 23490
57 22880
58 26145
59 24795
60 29694
61 27435
62 32040
63 30926
64 35433
65 33264
66 39600
67 36465
68 42714
69 40944
70 46260
71 43470
72 51870
73 47286
74 54891
75 52819
76 59955
77 55440
78 65982
79 60060
80 70029
81 66550
82 74970
83 69741
84 83216
85 75114
86 86625
87 82770
88 93465
89 86130
90 102069
91 91980
92 107190
93 101312
94 113436
95 105210
96 125055
97 111720
98 128574
99 122199

Some polynomials detect primes

In [5]:
f1 = lambda n: (n**2 - 3*n + 2)*(MacMahon(1, n))
f2 = lambda n: 8*MacMahon(2, n)
f = lambda n: f1(n) - f2(n)

In [6]:
for n in range(1, 101):
    print(n, f(n))

1 0
2 0
3 0
4 18
5 0
6 120
7 0
8 270
9 192
10 504
11 0
12 1680
13 0
14 1296
15 1536
16 2790
17 0
18 5160
19 0
20 6804
21 3840
22 4680
23 0
24 16800
25 2880
26 7560
27 7680
28 17280
29 0
30 30960
31 0
32 25110
33 13440
34 16416
35 13824
36 59490
37 0
38 22680
39 21504
40 66780
41 0
42 78720
43 0
44 61776
45 59136
46 39600
47 0
48 148800
49 16128
50 86184
51 46080
52 99540
53 0
54 159600
55 46080
56 168480
57 63360
58 78120
59 0
60 337344
61 0
62 95040
63 145920
64 212598
65 72576
66 282240
67 0
68 215460
69 109824
70 305568
71 0
72 554190
73 0
74 160056
75 247296
76 297360
77 103680
78 455280
79 0
80 585900
81 232320
82 216720
83 0
84 858816
85 152064
86 249480
87 215040
88 599040
89 0
90 1016136
91 161280
92 518400
93 261120
94 324576
95 207360
96 1249920
97 0
98 563760
99 505344
100 998694

In [7]:
g1 = lambda n: (3*n**3 - 13*n**2 + 18*n - 8)*(MacMahon(1, n))
g2 = lambda n: (12*n**2 - 120*n + 212)*(MacMahon(2,n))
g3 = lambda n: 960*(MacMahon(3,n))
g = lambda n: g1(n) + g2(n) - g3(n)

In [8]:
for n in range(1, 101):
    print(n, g(n))

1 0
2 0
3 0
4 108
5 0
6 1260
7 0
8 4860
9 2592
10 14364
11 0
12 51660
13 0
14 75816
15 43776
16 169020
17 0
18 367380
19 0
20 551124
21 213120
22 723060
23 0
24 1745100
25 108000
26 1666980
27 725760
28 2854440
29 0
30 5059800
31 0
32 5525820
33 1955520
34 6377616
35 808704
36 13324320
37 0
38 11124540
39 4483584
40 18193140
41 0
42 26245440
43 0
44 26927316
45 11604096
46 28927800
47 0
48 56580300
49 1185408
50 47906964
51 17072640
52 61957980
53 0
54 91186200
55 6289920
56 93574440
57 29747520
58 92220660
59 0
60 180886104
61 0
62 128731680
63 55215360
64 177800508
65 14043456
66 247605120
67 0
68 236575080
69 77261184
70 265912848
71 0
72 434332080
73 0
74 311869116
75 145426176
76 412439580
77 14463360
78 569663640
79 0
80 585858420
81 179184960
82 521103240
83 0
84 938298816
85 52233984
86 661246740
87 246113280
88 879121620
89 0
90 1253645316
91 30723840
92 1071775800
93 343503360
94 1031664816
95 90512640
96 1816467660
97 0
98 1314037080
99 499209984
100 1757460024

In [9]:
h1 = lambda n: (25*n**4 - 171*n**3 + 423*n**2 - 447*n + 170)*(MacMahon(1, n))
h2 = lambda n: (300*n**3 - 3554*n**2 + 12900*n - 14990)*(MacMahon(2,n))
h3 = lambda n: (2400*n**2 - 60480*n +214080)*(MacMahon(3,n))
h4 = lambda n: 725760*(MacMahon(4,n))
h = lambda n: h1(n) + h2(n) + h3(n) - h4(n)

In [10]:
for n in range(1, 101):
    print(n, h(n))

1 0
2 0
3 0
4 1080
5 0
6 24750
7 0
8 178200
9 58320
10 852390
11 0
12 3644550
13 0
14 9093060
15 2424960
16 24111000
17 0
18 61592850
19 0
20 117011790
21 24552000
22 217462050
23 0
24 480075750
25 6750000
26 701804250
27 142300800
28 1228065300
29 0
30 2245765500
31 0
32 3127944600
33 580658400
34 4600440360
35 86106240
36 8240915250
37 0
38 10028330550
39 1872541440
40 15130234350
41 0
42 23519023200
43 0
44 29097728010
45 5552285760
46 38232067500
47 0
48 61876923750
49 145212480
50 69473755890
51 12269664000
52 93742837650
53 0
54 136531741500
55 1773100800
56 158074780500
57 26744493600
58 193830660450
59 0
60 298295485740
61 0
62 309195176400
63 55005667200
64 401712848280
65 5661200160
66 556356276000
67 0
68 613395228600
69 101955522240
70 734801815080
71 0
72 1059177769650
73 0
74 1067203990710
75 198189048960
76 1336446168750
77 3841732800
78 1791795606300
79 0
80 1941133373550
81 314802612000
82 2189682803700
83 0
84 3118283451360
85 36883693440
86 3056306195250
87 516887078400
88 3735561076650
89 0
90 4939382268810
91 11736144000
92 5091822121500
93 824526547200
94 5696930768760
95 80326857600
96 7933888635750
97 0
98 7646300135100
99 1285310759040
100 9247056748290

Some Congruences

M_2(5n + 2) is divisible by 5

In [11]:
for n in range(1, 101):
  if (MacMahon(2, 5*n+2) % 5 == 0):
    print(n, (MacMahon(2, 5*n+2)), "Divisible by 5")

1 30 Divisible by 5
2 175 Divisible by 5
3 540 Divisible by 5
4 1305 Divisible by 5
5 2290 Divisible by 5
6 4185 Divisible by 5
7 5985 Divisible by 5
8 9840 Divisible by 5
9 12420 Divisible by 5
10 18795 Divisible by 5
11 22880 Divisible by 5
12 32040 Divisible by 5
13 36465 Divisible by 5
14 51870 Divisible by 5
15 55440 Divisible by 5
16 74970 Divisible by 5
17 82770 Divisible by 5
18 107190 Divisible by 5
19 111720 Divisible by 5
20 149310 Divisible by 5
21 150255 Divisible by 5
22 194370 Divisible by 5
23 202685 Divisible by 5
24 249705 Divisible by 5
25 252000 Divisible by 5
26 329280 Divisible by 5
27 316710 Divisible by 5
28 395010 Divisible by 5
29 404625 Divisible by 5
30 490275 Divisible by 5
31 477555 Divisible by 5
32 606210 Divisible by 5
33 575190 Divisible by 5
34 712305 Divisible by 5
35 708240 Divisible by 5
36 835380 Divisible by 5
37 808110 Divisible by 5
38 1024255 Divisible by 5
39 945945 Divisible by 5
40 1143675 Divisible by 5
41 1135290 Divisible by 5
42 1338525 Divisible by 5
43 1267200 Divisible by 5
44 1570350 Divisible by 5
45 1449225 Divisible by 5
46 1757475 Divisible by 5
47 1706720 Divisible by 5
48 1970415 Divisible by 5
49 1867530 Divisible by 5
50 2330450 Divisible by 5
51 2105280 Divisible by 5
52 2503215 Divisible by 5
53 2443410 Divisible by 5
54 2837430 Divisible by 5
55 2637525 Divisible by 5
56 3229920 Divisible by 5
57 2939580 Divisible by 5
58 3512040 Divisible by 5
59 3367680 Divisible by 5
60 3838950 Divisible by 5
61 3593205 Divisible by 5
62 4434990 Divisible by 5
63 3956715 Divisible by 5
64 4662720 Divisible by 5
65 4496690 Divisible by 5
66 5168835 Divisible by 5
67 4755660 Divisible by 5
68 5775555 Divisible by 5
69 5192595 Divisible by 5
70 6168825 Divisible by 5
71 5865120 Divisible by 5
72 6621615 Divisible by 5
73 6145140 Divisible by 5
74 7528640 Divisible by 5
75 6661620 Divisible by 5
76 7783920 Divisible by 5
77 7468175 Divisible by 5
78 8544555 Divisible by 5
79 7781895 Divisible by 5
80 9392160 Divisible by 5
81 8387550 Divisible by 5
82 9896250 Divisible by 5
83 9341360 Divisible by 5
84 10501155 Divisible by 5
85 9707340 Divisible by 5
86 11826190 Divisible by 5
87 10381680 Divisible by 5
88 12067650 Divisible by 5
89 11510850 Divisible by 5
90 13076370 Divisible by 5
91 11878230 Divisible by 5
92 14300640 Divisible by 5
93 12676365 Divisible by 5
94 14912325 Divisible by 5
95 14003955 Divisible by 5
96 15659820 Divisible by 5
97 14378310 Divisible by 5
98 17465070 Divisible by 5
99 15318720 Divisible by 5
100 17695125 Divisible by 5

M_3(7n + 3) and M_3(7n + 5) is divisible by 7

In [12]:
for n in range(1, 51):
  if (MacMahon(3, 7*n+3) % 7 == 0):
    print(n, (MacMahon(3, 7*n+3)), "Divisible by 7")

1 42 Divisible by 7
2 1134 Divisible by 7
3 7826 Divisible by 7
4 31668 Divisible by 7
5 94311 Divisible by 7
6 228137 Divisible by 7
7 492282 Divisible by 7
8 937251 Divisible by 7
9 1701399 Divisible by 7
10 2813517 Divisible by 7
11 4588983 Divisible by 7
12 6927697 Divisible by 7
13 10503318 Divisible by 7
14 14844060 Divisible by 7
15 21383418 Divisible by 7
16 28761348 Divisible by 7
17 39765033 Divisible by 7
18 51677549 Divisible by 7
19 69109992 Divisible by 7
20 87038721 Divisible by 7
21 113875006 Divisible by 7
22 139732593 Divisible by 7
23 178744293 Divisible by 7
24 215815271 Divisible by 7
25 270622737 Divisible by 7
26 320579343 Divisible by 7
27 398007078 Divisible by 7
28 463488795 Divisible by 7
29 566624331 Divisible by 7
30 655039518 Divisible by 7
31 790182897 Divisible by 7
32 900838260 Divisible by 7
33 1081409336 Divisible by 7
34 1218241794 Divisible by 7
35 1446623388 Divisible by 7
36 1624124502 Divisible by 7
37 1907514609 Divisible by 7
38 2119900167 Divisible by 7
39 2488172582 Divisible by 7
40 2737137543 Divisible by 7
41 3182408649 Divisible by 7
42 3500971138 Divisible by 7
43 4037197752 Divisible by 7
44 4401157761 Divisible by 7
45 5077339659 Divisible by 7
46 5493351402 Divisible by 7
47 6291469926 Divisible by 7
48 6812420132 Divisible by 7
49 7740903387 Divisible by 7
50 8323775460 Divisible by 7

In [13]:
for n in range(1, 51):
  if (MacMahon(3, 7*n+5) % 7 == 0):
    print(n, (MacMahon(3, 7*n+5)), "Divisible by 7")

1 140 Divisible by 7
2 2142 Divisible by 7
3 12159 Divisible by 7
4 44149 Divisible by 7
5 123879 Divisible by 7
6 286902 Divisible by 7
7 599452 Divisible by 7
8 1113861 Divisible by 7
9 1984878 Divisible by 7
10 3233041 Divisible by 7
11 5212347 Divisible by 7
12 7777539 Divisible by 7
13 11706870 Divisible by 7
14 16405935 Divisible by 7
15 23455467 Divisible by 7
16 31450986 Divisible by 7
17 43196076 Divisible by 7
18 55783728 Divisible by 7
19 74557518 Divisible by 7
20 93379083 Divisible by 7
21 121581180 Divisible by 7
22 149301243 Divisible by 7
23 190035615 Divisible by 7
24 228376827 Divisible by 7
25 287078624 Divisible by 7
26 338499126 Divisible by 7
27 418327308 Divisible by 7
28 488732167 Divisible by 7
29 595167258 Divisible by 7
30 684902295 Divisible by 7
31 828951095 Divisible by 7
32 941596908 Divisible by 7
33 1126329057 Divisible by 7
34 1273613866 Divisible by 7
35 1505912772 Divisible by 7
36 1684434528 Divisible by 7
37 1988495187 Divisible by 7
38 2200500162 Divisible by 7
39 2571827202 Divisible by 7
40 2844645538 Divisible by 7
41 3295891809 Divisible by 7
42 3610391400 Divisible by 7
43 4183083450 Divisible by 7
44 4545451911 Divisible by 7
45 5227589367 Divisible by 7
46 5682650589 Divisible by 7
47 6481054419 Divisible by 7
48 6994868328 Divisible by 7
49 7997934679 Divisible by 7
50 8564686452 Divisible by 7